### ISSUE TITLE
Improve Handling where an Organization is DIC and DMS in one DUP

### ISSUE THREAD

**Issue by schwzr** [medizininformatik-initiative/mii-process-data-sharing#32]
## Scenario
A DUP (Data Use Project) is performed and therefore a new instance of the data sharing process is started.
In this DUP, a location will be the DMS (Data Management Site) on the one hand and provide data itself on the other.

## Current Situation
If a DUP is performed in the current release, a new instance of the data sharing process is started.
Among other things, the DMS to be used (via its organization identifier) and a list of DICs (via their organization identifiers) are defined in the start task resource.
Tasks are then created on the DMS and on the DICs. The task starts the process at the DICs, which create a QuestionaireResponse resource in order to have the data release confirmed by an employee in the DIC. After confirmation, the process is continued and a data transfer to the DMS is initiated.
If the DIC is identical to the DMS, the data transfer fails and a new QuestionaireResponse resource is created with the request for confirmation. The data transfer fails because the process in the DIC is not authorized to transfer the data to the DMS (same organization) (see https://github.com/medizininformatik-initiative/mii-process-data-sharing/blob/v1.0.1.1/src/main/resources/fhir/ActivityDefinition/data-sharing-merge.xml#L87).

This status currently cannot be resolved.

## Possible Solutions
Three different scenarios are conceivable here.

### Variant 1: Allow DIC to be in DMS in the same DUP

It is permitted that a DIC in the same DUP is also a DMS. Here, the process should be adapted so that the data can be received internally (adaptation of the ActivityDefinition necessary -> new FHIR resources -> 1.1.x.x release).

### Variant 2: Prohibit DIC from being DMS in the same DUP (organizational)
A clean separation between DIC and DMS is enforced organizationally; in future, it should no longer be possible for a data-providing location in a DUP to also be a DMS.

The process should be adapted so that no incorrect process configuration is possible.

### Variant 3: Prohibit DIC from being DMS in the same DUP (via DSF MII Data Sharing)
It should be prevented that a DIC, which is also DMS in the same DUP, can send the data via the MII Data Sharing process plugin. However, it should be possible within the DUP to insert data into the DMS in a different way.

Here, the process should be adapted so that no incorrect process execution configuration is possible.

**Comment by wetret** [comment]
I decided to go with variant 1 as this is also implemented in the data-transfer process.
